version: '3'

services:
  rails:
    build: .
    environment:
      TZ: "Japan"
    container_name: "olive-app"
    ports:
      - "8080:3000"
      - "8035:3035"
    volumes:
      - ./src/:/usr/local/src
      - bundle-data:/usr/local/bundle
    depends_on:
      - mysql
    tty: true
    stdin_open: true

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: "olive-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'db_olive'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'mysql'
      TZ: "Asia/Tokyo"
    ports: 
      - 3360:3306
    volumes: 
      - db-data:/var/lib/mysql

volumes:
  bundle-data:
    driver: 'local'
  db-data:
    driver: 'local'