employment_type:
  - 正社員
  - 契約社員
  - パート・アルバイト

has_registration_card:
  "未": false
  "済": true

store_type:
  "直営店": "owned"
  "FC店": "franchised"
  "FC_札幌_國分": "franchised_sapporo_kokubun"
  "FC_テスト_東京": "franchised_tokyo_test"

stores:
  head_store_id: 1
  head_este_store_id: 2
  time_options:
    - '09:00:00'
    - '10:00:00'
    - '11:00:00'
    - '12:00:00'
    - '13:00:00'
    - '14:00:00'
    - '15:00:00'
    - '16:00:00'
    - '17:00:00'
    - '18:00:00'
    - '19:00:00'
    - '20:00:00'

reservations:
  staff_options:
    '指定なし': ''
    '担当者なし': 'none'
    '担当者あり': 'any'
  order_options:
    'ID': 'id'
    '予約日時': 'reserved_at'

brand:
  name: '女性専門の治療院オリーヴボディケア'
  system_email: 'no-reply@olivebodycare.healthcare'

audit:
  changed_by:
   '顧客': 'Customer'
   '店舗': 'Staff'

domain:
  production: 'dashboard.olivebodycare.healthcare'
  reserve: 'reserve.olivebodycare.healthcare'

customer:
  common_email: 'common.mail@olivebodycare.healthcare'

duplicated_customer:
  kana:
    name: 'カナ'
    columns:
      - first_kana
      - last_kana
  tel:
    name: '電話番号'
    columns:
      - tel
  kana_tel:
    name: 'カナと電話番号'
    columns:
      - first_kana
      - last_kana
      - tel
