employment_type:
  - 正社員
  - 契約社員
  - パート・アルバイト

has_registration_card:
  "未": false
  "済": true

store_type:
  "直営店": "owned"
  "FC店": "franchised"

stores:
  head_store_id: 1
  head_este_store_id: 2

reservations:
  staff_options:
    '指定なし': ''
    '担当者なし': 'none'
    '担当者あり': 'any'
  order_options:
    'ID': 'id'
    '予約日時': 'reserved_at'

reservation_at_options:
  - '10:00:00'
  - '11:00:00'
  - '12:00:00'
  - '13:00:00'
  - '16:00:00'
  - '17:00:00'
  - '18:00:00'
  - '19:00:00'

brand:
  name: '女性専門の治療院オリーヴボディケア'
  system_email: 'no-reply@olivebodycare.healthcare'

audit:
  changed_by:
   '顧客': 'Customer'
   '店舗': 'Staff'