employment_type:
  - 正社員
  - 契約社員
  - パート・アルバイト

has_registration_card:
  "未": false
  "済": true

store_type:
  "直営店": "owned"
  "FC店": "franchised"

stores:
  head_store_id: 1
  head_este_store_id: 2

reservation_at_options:
  - '10:00:00'
  - '10:30:00'
  - '11:00:00'
  - '11:30:00'
  - '12:00:00'
  - '12:30:00'
  - '13:00:00'
  - '16:00:00'
  - '16:30:00'
  - '17:00:00'
  - '17:30:00'
  - '18:00:00'
  - '18:30:00'
  - '19:00:00'

brand_name: 'オリーブボディケア'
