Customer.where(id: 1).first_or_create(
    costomer_id:1, 
    first_name:'高橋', 
    last_name:'顧客1', 
    first_kana:'高橋',
    last_kana:'こきゃく１', 
    tel:'090-0000-0000', 
    pc_mail:'tt.wing001@gmail.com', 
    sp_mail:'tt.wing003@gmail.com', 
    can_receive_mail: true, 
    birthday:'1985-1-1', 
    zip_code:'160-0022', 
    prefecture:'東京都', 
    city:'新宿区新宿１−１−１　なんとかビル１階', 
    address:'東京都	新宿区新宿１−１−１　なんとかビル１階', 
    has_membership: true, 
    comment1:'コメントです', 
    fitsrt_visit_store_id:1, 
    last_visit_store_id:2, 
    first_visit_at:'2019-01-01', 
    last_visit_at:'2019-02-01',
    medical_record_no: 999,
    children_count: 1,
    occupation_id: 1,
    zoomancy_id: 1,
    baby_age_id: 1,
    visit_reason: 1,
    introducer: '山田',
    searchd_by: 'オリーブ',
    nearest_station_id: 1,
    size_id: 1,
    has_registration_card: false
)