inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb

#################### Layout ###########################

Layout/EndOfLine:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
