AllCops:
  Exclude:
    - db/schema.rb
    - bin/*

#################### Layout ###########################

Layout/AlignArguments:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/IndentFirstArrayElement:
  Enabled: false

Layout/IndentFirstHashElement:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

#################### Lint ###########################

Lint/HandleExceptions:
  Enabled: false

#################### Metrics ###########################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

#################### Naming ###########################

Naming/PredicateName:
  Enabled: false

#################### Style ###########################

Style/AsciiComments:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SymbolProc:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets
