inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb

#################### Layout ###########################

Layout/ArgumentAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

#################### Lint ###########################

Lint/SuppressedException:
  Enabled: false
