Cigarette.where(id: 1).first_or_create!(name: '吸わない')
Cigarette.where(id: 2).first_or_create!(name: 'たまに吸う')
Cigarette.where(id: 3).first_or_create!(name: '吸う')
Cigarette.where(id: 4).first_or_create!(name: '凄く吸う')
Cigarette.where(id: 5).first_or_create!(name: 'その他')