CurrentHospital.where(id: 1).first_or_create!(name: '整骨・整体院')
CurrentHospital.where(id: 2).first_or_create!(name: '整形外科')
CurrentHospital.where(id: 3).first_or_create!(name: '内科')
CurrentHospital.where(id: 4).first_or_create!(name: '産婦人科')
CurrentHospital.where(id: 5).first_or_create!(name: '眼科')
CurrentHospital.where(id: 6).first_or_create!(name: '心療内科')
CurrentHospital.where(id: 7).first_or_create!(name: '皮膚科')
CurrentHospital.where(id: 8).first_or_create!(name: 'その他')
