GoalTherapyMenu.where(id: 1).first_or_create!(name:'姿勢改善')
GoalTherapyMenu.where(id: 2).first_or_create!(name:'姿勢改善')
GoalTherapyMenu.where(id: 3).first_or_create!(name:'体質改善')
GoalTherapyMenu.where(id: 4).first_or_create!(name:'根本治療')
GoalTherapyMenu.where(id: 5).first_or_create!(name:'リハビリ')
GoalTherapyMenu.where(id: 6).first_or_create!(name:'ボディケア')
GoalTherapyMenu.where(id: 7).first_or_create!(name:'その他')