Occupation.where(id: 1).first_or_create!(name: '専業主婦')
Occupation.where(id: 2).first_or_create!(name: '主婦（育児休暇中）')
Occupation.where(id: 3).first_or_create!(name: '会社員')
Occupation.where(id: 4).first_or_create!(name: 'パート・アルバイト')
Occupation.where(id: 5).first_or_create!(name: '派遣社員')
Occupation.where(id: 6).first_or_create!(name: '学生')
Occupation.where(id: 7).first_or_create!(name: '自営業')
Occupation.where(id: 8).first_or_create!(name: 'その他')