Skill.where(id: 1).first_or_create(name:'整体・マッサージ')
Skill.where(id: 2).first_or_create(name:'鍼灸')
Skill.where(id: 3).first_or_create(name:'交通事故治療')
Skill.where(id: 4).first_or_create(name:'不妊治療')
Skill.where(id: 5).first_or_create(name:'エステ')
