Skill.find_or_initialize_by(skill_id:1, name:'整体・マッサージ')
Skill.find_or_initialize_by(skill_id:2, name:'鍼灸')
Skill.find_or_initialize_by(skill_id:3, name:'交通事故治療')
Skill.find_or_initialize_by(skill_id:4, name:'不妊治療')
Skill.find_or_initialize_by(skill_id:4, name:'エステ')