Staff.create(staff_id:1, first_name:'整体', last_name:'太郎', first_name_kana:'セイタイ', last_name_kana:'タロウ', staff_skill_id:1
, belong_store_id:, role_id:, employee_type:'', absence_flg:false, deleted_flg:false)
Staff.create(staff_id:2, first_name:'整体', last_name:'花子', first_name_kana:'セイタイ', last_name_kana:'ハナコ', staff_skill_id:1
, belong_store_id:, role_id:, employee_type:'', absence_flg:false, deleted_flg:false)
Staff.create(staff_id:3, first_name:'鍼灸', last_name:'次郎', first_name_kana:'シンキュウ', last_name_kana:'ジロウ', staff_skill_id:2
, belong_store_id:, role_id:, employee_type:'', absence_flg:false, deleted_flg:false)
Staff.create(staff_id:4, first_name:'交通', last_name:'三郎', first_name_kana:'コウツウ', last_name_kana:'サブロウ', staff_skill_id:3
, belong_store_id:, role_id:, employee_type:'', absence_flg:false, deleted_flg:false)
Staff.create(staff_id:５, first_name:'不妊', last_name:'四郎', first_name_kana:'フニン', last_name_kana:'シロウ', staff_skill_id:4
, belong_store_id:, role_id:, employee_type:'', absence_flg:false, deleted_flg:false)