TreatGoal.where(id: 1).first_or_create!(name: '姿勢改善')
TreatGoal.where(id: 2).first_or_create!(name: '痛みを取る')
TreatGoal.where(id: 3).first_or_create!(name: '体質改善')
TreatGoal.where(id: 4).first_or_create!(name: '根本治療')
TreatGoal.where(id: 5).first_or_create!(name: 'リハビリ')
TreatGoal.where(id: 6).first_or_create!(name: 'ボディケア')
TreatGoal.where(id: 7).first_or_create!(name: 'その他')