VisitHistory.where(id: 1).first_or_create(name:'広告・チラシ')
VisitHistory.where(id: 2).first_or_create(name:'看板・通りがかり')
VisitHistory.where(id: 3).first_or_create(name:'雑誌')
VisitHistory.where(id: 4).first_or_create(name:'知人の紹介')
VisitHistory.where(id: 5).first_or_create(name:'Web検索')
VisitHistory.where(id: 6).first_or_create(name:'その他')