Zoomancy.where(id: 1).first_or_create!(name: 'S　長距離ランナーのチータ')
Zoomancy.where(id: 2).first_or_create!(name: 'M　社交家のたぬき')
Zoomancy.where(id: 3).first_or_create!(name: 'E　落ち着きのない猿')
Zoomancy.where(id: 4).first_or_create!(name: 'E　フットワークの軽いコアラ')
Zoomancy.where(id: 5).first_or_create!(name: 'M　面倒見のよい黒ひょう')
Zoomancy.where(id: 6).first_or_create!(name: 'E　愛情あふれるトラ')
Zoomancy.where(id: 7).first_or_create!(name: 'S　全力疾走するチータ')
Zoomancy.where(id: 8).first_or_create!(name: 'M　磨きあげられたたぬき')
Zoomancy.where(id: 9).first_or_create!(name: 'E　大きな志をもった猿')
Zoomancy.where(id: 10).first_or_create!(name: 'E　母性豊かなコアラ')
Zoomancy.where(id: 11).first_or_create!(name: 'M　正直なこじか')
Zoomancy.where(id: 12).first_or_create!(name: 'S　人気者のゾウ')
Zoomancy.where(id: 13).first_or_create!(name: 'E　ネアカの狼')
Zoomancy.where(id: 14).first_or_create!(name: 'M　協調性のないひつじ')
Zoomancy.where(id: 15).first_or_create!(name: 'E　どっしりした猿')
Zoomancy.where(id: 16).first_or_create!(name: 'E　コアラの中のコアラ')
Zoomancy.where(id: 17).first_or_create!(name: 'M　強い意思をもったこじか')
Zoomancy.where(id: 18).first_or_create!(name: 'S　デリケートなゾウ')
Zoomancy.where(id: 19).first_or_create!(name: 'E　放浪の狼')
Zoomancy.where(id: 20).first_or_create!(name: 'M　物静かなひつじ')
Zoomancy.where(id: 21).first_or_create!(name: 'S　落ち着きのあるペガサス')
Zoomancy.where(id: 22).first_or_create!(name: 'S　強靭な翼をもつペガサス')
Zoomancy.where(id: 23).first_or_create!(name: 'M　無邪気なひつじ')
Zoomancy.where(id: 24).first_or_create!(name: 'E　クリエイティブな狼')
Zoomancy.where(id: 25).first_or_create!(name: 'E　穏やかな狼')
Zoomancy.where(id: 26).first_or_create!(name: 'M　粘り強いひつじ')
Zoomancy.where(id: 27).first_or_create!(name: 'S　波乱に満ちたペガサス')
Zoomancy.where(id: 28).first_or_create!(name: 'S　優雅なペガサス')
Zoomancy.where(id: 29).first_or_create!(name: 'M　チャレンジ精神旺盛なひつじ')
Zoomancy.where(id: 30).first_or_create!(name: 'E　順応性のある狼')
Zoomancy.where(id: 31).first_or_create!(name: 'S　リーダーとなるゾウ')
Zoomancy.where(id: 32).first_or_create!(name: 'M　しっかり者のこじか')
Zoomancy.where(id: 33).first_or_create!(name: 'E　活動的なコアラ')
Zoomancy.where(id: 34).first_or_create!(name: 'E　気分屋の猿')
Zoomancy.where(id: 35).first_or_create!(name: 'M　頼られると嬉しいひつじ')
Zoomancy.where(id: 36).first_or_create!(name: 'E　好感をもたれる狼')
Zoomancy.where(id: 37).first_or_create!(name: 'S　まっしぐらに突き進むゾウ')
Zoomancy.where(id: 38).first_or_create!(name: 'M　華やかなこじか')
Zoomancy.where(id: 39).first_or_create!(name: 'E　夢とロマンのコアラ')
Zoomancy.where(id: 40).first_or_create!(name: 'E　尽くす猿')
Zoomancy.where(id: 41).first_or_create!(name: 'M　大器晩成のたぬき')
Zoomancy.where(id: 42).first_or_create!(name: 'S　足腰の強いチータ')
Zoomancy.where(id: 43).first_or_create!(name: 'E　動きまわるトラ')
Zoomancy.where(id: 44).first_or_create!(name: 'M　情熱的なくろひょう')
Zoomancy.where(id: 45).first_or_create!(name: 'E　サービス精神旺盛なコアラ')
Zoomancy.where(id: 46).first_or_create!(name: 'E　守りの猿')
Zoomancy.where(id: 47).first_or_create!(name: 'M　人間味あるれるたぬき')
Zoomancy.where(id: 48).first_or_create!(name: 'S　品格のあるチータ')
Zoomancy.where(id: 49).first_or_create!(name: 'E　ゆったり悠然としたトラ')
Zoomancy.where(id: 50).first_or_create!(name: 'M　落ち込みの激しい黒ひょう')
Zoomancy.where(id: 51).first_or_create!(name: 'S　わが道をゆくライオン')
Zoomancy.where(id: 52).first_or_create!(name: 'S　統率力のあるライオン')
Zoomancy.where(id: 53).first_or_create!(name: 'M　感情豊かなくろひょう')
Zoomancy.where(id: 54).first_or_create!(name: 'E　楽天的なトラ')
Zoomancy.where(id: 55).first_or_create!(name: 'E　パワフルなトラ')
Zoomancy.where(id: 56).first_or_create!(name: 'M　気どらないくろひょう')
Zoomancy.where(id: 57).first_or_create!(name: 'S　感情的なライオン')
Zoomancy.where(id: 58).first_or_create!(name: 'S　傷つきやすいライオン')
Zoomancy.where(id: 59).first_or_create!(name: 'M　束縛を嫌うくろひょう')
Zoomancy.where(id: 60).first_or_create!(name: 'E　慈悲深いトラ')
Zoomancy.find_by(id: 1).update(name: 'Sun T+ チーター')
Zoomancy.find_by(id: 2).update(name: 'Moon T- たぬき')
Zoomancy.find_by(id: 3).update(name: 'Earth F+ 狼')
Zoomancy.find_by(id: 4).update(name: 'Earth F- コアラ')
Zoomancy.find_by(id: 5).update(name: 'Moon E+ 黒ひょう')
Zoomancy.find_by(id: 6).update(name: 'Earth E- トラ')
Zoomancy.find_by(id: 7).update(name: 'Sun M+ チータ')
Zoomancy.find_by(id: 8).update(name: 'Moon M- たぬき')
Zoomancy.find_by(id: 9).update(name: 'Earth W+ 猿')
Zoomancy.find_by(id: 10).update(name: 'Earth W- コアラ')
Zoomancy.find_by(id: 11).update(name: 'Moon T+ こじか')
Zoomancy.find_by(id: 12).update(name: 'Sun T- ゾウ')
Zoomancy.find_by(id: 13).update(name: 'Earth F+ 狼')
Zoomancy.find_by(id: 14).update(name: 'Moon F- ひつじ')
Zoomancy.find_by(id: 15).update(name: 'Earth E+ 猿')
Zoomancy.find_by(id: 16).update(name: 'Earth E- コアラ')
Zoomancy.find_by(id: 17).update(name: 'Moon M+ こじか')
Zoomancy.find_by(id: 18).update(name: 'Sun M- ゾウ')
Zoomancy.find_by(id: 19).update(name: 'Earth W+ 狼')
Zoomancy.find_by(id: 20).update(name: 'Moon W- ひつじ')
Zoomancy.find_by(id: 21).update(name: 'Sun T+ ペガサス')
Zoomancy.find_by(id: 22).update(name: 'Sun T- ペガサス')
Zoomancy.find_by(id: 23).update(name: 'Moon F+ ひつじ')
Zoomancy.find_by(id: 24).update(name: 'Earth F- 狼')
Zoomancy.find_by(id: 25).update(name: 'Earth E+ 狼')
Zoomancy.find_by(id: 26).update(name: 'Moon E- ひつじ')
Zoomancy.find_by(id: 27).update(name: 'Sun M+ ペガサス')
Zoomancy.find_by(id: 28).update(name: 'Sun M- ペガサス')
Zoomancy.find_by(id: 29).update(name: 'Moon W+ ひつじ')
Zoomancy.find_by(id: 30).update(name: 'Earth W- 狼')
Zoomancy.find_by(id: 31).update(name: 'Sun T+ ゾウ')
Zoomancy.find_by(id: 32).update(name: 'Moon T- こじか')
Zoomancy.find_by(id: 33).update(name: 'Earth F+ コアラ')
Zoomancy.find_by(id: 34).update(name: 'Earth F- 猿')
Zoomancy.find_by(id: 35).update(name: 'Moon E+ ひつじ')
Zoomancy.find_by(id: 36).update(name: 'Earth E- 狼')
Zoomancy.find_by(id: 37).update(name: 'Sun M+ ゾウ')
Zoomancy.find_by(id: 38).update(name: 'Moon M- こじか')
Zoomancy.find_by(id: 39).update(name: 'Earth W+ コアラ')
Zoomancy.find_by(id: 40).update(name: 'Earth W- 猿')
Zoomancy.find_by(id: 41).update(name: 'Moon T+ たぬき')
Zoomancy.find_by(id: 42).update(name: 'Sun T- チータ')
Zoomancy.find_by(id: 43).update(name: 'Earth F+ トラ')
Zoomancy.find_by(id: 44).update(name: 'Moon F- 黒ひょう')
Zoomancy.find_by(id: 45).update(name: 'Earth E+ コアラ')
Zoomancy.find_by(id: 46).update(name: 'Earth E- 猿')
Zoomancy.find_by(id: 47).update(name: 'Moon M+ たぬき')
Zoomancy.find_by(id: 48).update(name: 'Sun M- チータ')
Zoomancy.find_by(id: 49).update(name: 'Earth W+ トラ')
Zoomancy.find_by(id: 50).update(name: 'Moon W- 黒ひょう')
Zoomancy.find_by(id: 51).update(name: 'Sun T+ ライオン')
Zoomancy.find_by(id: 52).update(name: 'Sun T- ライオン')
Zoomancy.find_by(id: 53).update(name: 'Moon F+ 黒ひょう')
Zoomancy.find_by(id: 54).update(name: 'Earth F- トラ')
Zoomancy.find_by(id: 55).update(name: 'Earth E+ トラ')
Zoomancy.find_by(id: 56).update(name: 'Moon E- 黒ひょう')
Zoomancy.find_by(id: 57).update(name: 'Sun M+ ライオン')
Zoomancy.find_by(id: 58).update(name: 'Sun M- ライオン')
Zoomancy.find_by(id: 59).update(name: 'Moon W+ 黒ひょう')
Zoomancy.find_by(id: 60).update(name: 'Earth W- トラ')