name: stg build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: bundle install
        run: bundle install
        working-directory: ./src
      - name: execute build
        run: bash build.command
      - name: Upload Build Zip
        uses: actions/upload-artifact@v2
        with:
          name: src
          path: src.zip
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: src
