name: stg build

on: push
  #push:
    #branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: execute build
        run: bash build.command
      - name: Upload Build Zip
        uses: actions/upload-artifact@v2
        with:
          name: src.zip
          path: src.zip
      - name: Download artifacts
        uses: actions/download-artifact@v2
